# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
# metadata:
#   name: rollout-example
# spec:
#  replicas: 2
#  revisionHistoryLimit: 2
#  selector:
#    matchLabels:
#      app: myapp
#  template:
#    metadata:
#      labels:
#        app: myapp
#    spec:
#      containers:
#      - name: weather-app
#        image: docker.io/atulinfracloud/weathersample:v1
#        imagePullPolicy: Always
#        ports:
#        - containerPort: 3000
#   strategy:
#     canary:
#       trafficRouting:
#         istio:
#           virtualService:
#             name: myapp       # Update with your Istio VirtualService name
#             routes:
#             - primary
#           destinationRule:
#             name: myapp       # Update with your Istio DestinationRule name
#             canarySubsetName: v2
#             stableSubsetName: v1
#       steps:
#       - setWeight: 10
#       - pause:
#           duration: 2m
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-example
spec:
 replicas: 2
 revisionHistoryLimit: 2
 selector:
   matchLabels:
     app: myapp
 template:
   metadata:
     labels:
       app: myapp
   spec:
     containers:
     - name: weather-app
       image: docker.io/atulinfracloud/weathersample:v1
       imagePullPolicy: Always
       ports:
       - containerPort: 3000
 strategy:
   canary:
     trafficRouting:
       istio:
         virtualService:
           name: myapp    # Update with your Istio VirtualService name
           routes:
           - primary
         destinationRule:
           name: myapp       # Update with your Istio DestinationRule name
           canarySubsetName: canary  # required
           stableSubsetName: stable
     steps:
     - setWeight: 10
     - pause:
         duration: 2m

